name: Just build

on:
  push:
    branches:
      - main

env:
  QT_VERSION: 6.8.3

jobs:
  build-on-ubuntu-latest:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      QT_HOST: linux
      QT_ARCH: linux_gcc_64
      QT_SPEC: gcc_64
    steps:
      - uses: actions/checkout@master
      - name: Install aqt
        run: pip install aqtinstall
      - name: Install QT
        run: |
          aqt list-qt ${{env.QT_HOST}} desktop --arch ${{env.QT_VERSION}}
          aqt install-qt ${{env.QT_HOST}} desktop ${{env.QT_VERSION}} ${{env.QT_ARCH}}
      - name: Install Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libgl1-mesa-dev
      - name: Try to build
        run: |
          cd sources
          ./../${{env.QT_VERSION}}/${{env.QT_SPEC}}/bin/qmake QLumEdit.pro
          make -j$(nproc)
  build-on-macos-latest:
    runs-on: macos-latest
    timeout-minutes: 15
    env:
      QT_HOST: mac
      QT_ARCH: clang_64
      QT_SPEC: macos
    steps:
      - uses: actions/checkout@master
      - name: Install aqt
        run: pip install aqtinstall
      - name: Install QT
        run: |
          aqt list-qt ${{env.QT_HOST}} desktop --arch ${{env.QT_VERSION}}
          aqt install-qt ${{env.QT_HOST}} desktop ${{env.QT_VERSION}} ${{env.QT_ARCH}}
      - name: Try to build
        run: |
          cd sources
          ./../${{env.QT_VERSION}}/${{env.QT_SPEC}}/bin/qmake QLumEdit.pro
          make -j$(sysctl -n hw.ncpu)
  build-on-windows-latest:
    runs-on: windows-latest
    timeout-minutes: 15
    env:
      QT_HOST: windows
      QT_ARCH: win64_msvc2022_64
      QT_SPEC: msvc2022_64
    steps:
      - uses: actions/checkout@master
      - name: Install aqt
        run: pip install aqtinstall
      - name: Install QT
        run: |
          aqt list-qt ${{env.QT_HOST}} desktop --arch ${{env.QT_VERSION}}
          aqt install-qt ${{env.QT_HOST}} desktop ${{env.QT_VERSION}} ${{env.QT_ARCH}}
      - name: Try to build
        shell: cmd
        run: |
          cd sources
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          "..\${{env.QT_VERSION}}\${{env.QT_SPEC}}\bin\qmake.exe" QLumEdit.pro
          nmake release