name: Just build

on:
  push:
    branches:
      - main

env:
  QT_VERSION: 6.2.2

jobs:
  build-on-ubuntu-latest:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      QT_ARCH: linux desktop
      QT_SPEC: gcc_64
    steps:
      - uses: actions/checkout@master
      - name: Install Prerequisites
        run: sudo apt-get install build-essential libgl1-mesa-dev
      - name: Install aqt
        run: pip install aqtinstall
      - name: Install QT
        run: |
          aqt list-qt ${{env.QT_ARCH}} --arch ${{env.QT_VERSION}}
          aqt install-qt ${{env.QT_ARCH}} ${{env.QT_VERSION}} ${{env.QT_SPEC}}
      - name: Try to build
        run: |
          cd sources
          ./../${{env.QT_VERSION}}/${{env.QT_SPEC}}/bin/qmake QLumEdit.pro
          make
  build-on-macos-latest:
    runs-on: macos-11
    timeout-minutes: 15
    env:
      AQT_VERSION: 2.0.6
      QT_SPEC: clang_64
    steps:
      - uses: actions/checkout@master
      - name: Install QT
        uses: jurplel/install-qt-action@v2
        with:
          aqtversion: '==${{env.AQT_VERSION}}'
          version: ${{env.QT_VERSION}}
          arch: ${{env.QT_SPEC}}
          dir: '.'
      - name: Try to build
        run: |
          cd sources
          ../Qt/${{env.QT_VERSION}}/macos/bin/qmake QLumEdit.pro
          make
  build-on-windows-latest:
    runs-on: windows-2022
    timeout-minutes: 15
    env:
      QT_ARCH: windows desktop
      QT_SPEC: msvc2019_64
    steps:
      - uses: actions/checkout@master
      - name: Install aqt
        run: pip install aqtinstall
      - name: Install QT
        run: |
          aqt list-qt ${{env.QT_ARCH}} --arch ${{env.QT_VERSION}}
          aqt install-qt ${{env.QT_ARCH}} ${{env.QT_VERSION}} win64_${{env.QT_SPEC}}
      - name: Try to build
        shell: cmd
        run: |
          cd sources
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          "..\${{env.QT_VERSION}}\${{env.QT_SPEC}}\bin\qmake.exe" QLumEdit.pro
          nmake release